#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppMsg.Droid.Sample.Resource", IsApplication=true)]

namespace AppMsg.Droid.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AppMsg.Droid.Resource.Color.monodroid_appmsg_alert = global::AppMsg.Droid.Sample.Resource.Color.monodroid_appmsg_alert;
			global::AppMsg.Droid.Resource.Color.monodroid_appmsg_confirm = global::AppMsg.Droid.Sample.Resource.Color.monodroid_appmsg_confirm;
			global::AppMsg.Droid.Resource.Color.monodroid_appmsg_error = global::AppMsg.Droid.Sample.Resource.Color.monodroid_appmsg_error;
			global::AppMsg.Droid.Resource.Color.monodroid_appmsg_fail = global::AppMsg.Droid.Sample.Resource.Color.monodroid_appmsg_fail;
			global::AppMsg.Droid.Resource.Color.monodroid_appmsg_info = global::AppMsg.Droid.Sample.Resource.Color.monodroid_appmsg_info;
			global::AppMsg.Droid.Resource.Color.monodroid_appmsg_success = global::AppMsg.Droid.Sample.Resource.Color.monodroid_appmsg_success;
			global::AppMsg.Droid.Resource.Layout.monodroid_app_msg = global::AppMsg.Droid.Sample.Resource.Layout.monodroid_app_msg;
			global::AppMsg.Droid.Resource.String.ApplicationName = global::AppMsg.Droid.Sample.Resource.String.ApplicationName;
			global::AppMsg.Droid.Resource.String.Hello = global::AppMsg.Droid.Sample.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int monodroid_appmsg_alert = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int monodroid_appmsg_confirm = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int monodroid_appmsg_error = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int monodroid_appmsg_fail = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int monodroid_appmsg_info = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int monodroid_appmsg_success = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MyButton1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MyButton2 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int MyButton3 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int MyButton4 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int MyButton5 = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int monodroid_app_msg = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
